# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4764d5ac5177a116e295787fd339d64b"
application_url = "https://reuters-generation-relate-generous.trycloudflare.com"
embedded = true
name = "Pearlbot-App"
handle = "pearlbot-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_script_tags"

[auth]
redirect_urls = [
  "https://reuters-generation-relate-generous.trycloudflare.com/auth/callback",
  "https://reuters-generation-relate-generous.trycloudflare.com/auth/shopify/callback",
  "https://reuters-generation-relate-generous.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
